language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t damianpm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damianpm/react-test npm test

after_success:
  - docker build -t damianpm/multi-client ./client
  - docker build -t damianpm/multi-nginx ./nginx
  - docker build -t damianpm/multi-server ./server
  - docker build -t damianpm/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push damianpm/multi-client
  - docker push damianpm/multi-nginx
  - docker push damianpm/multi-server
  - docker push damianpm/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-653043762694
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY